name: sine-nomine
version: 0.0.0

dependencies:
  - ansi-terminal
  - base
  - containers
  - inspection-testing
  - mtl
  - parallel
  - random
  - template-haskell
  - tasty
  - tasty-hunit
  - th-abstraction

library:
  source-dirs: ./src
  ghc-options:
    -Wall
    -threaded
    -rtsopts
    -with-rtsopts=-N8

tests:
  spec:
    main: Main.hs
    source-dirs: ./tests
    dependencies: sine-nomine
